#!/usr/bin/env python3
"""Render the repository adapter's self-contained GitHub quality workflow."""
import argparse
import json
from pathlib import Path

PINS = {
    'checkout': '3d3c42e5aac5ba805825da76410c181273ba90b1',
    'setup-node': '820762786026740c76f36085b0efc47a31fe5020',
    'setup-python': '5fda3b95a4ea91299a34e894583c3862153e4b97',
    'upload-artifact': '043fb46d1a93c77aae656e7c1c64a875d1fc6a0a',
    'download-artifact': '3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c',
    'cache': '55cc8345863c7cc4c66a329aec7e433d2d1c52a9',
}

TEMPLATE = '''# Generated by .quality/workflow.py from .quality.json; regenerate after adapter changes.
name: Quality
run-name: Quality ${{ inputs.request_id || format('{0} · {1}', github.event_name, github.event.pull_request.number || github.ref_name) }}
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [@@BRANCH@@]
  schedule:
    - cron: '@@MINUTE@@ 2 * * *'
      timezone: America/Denver
  workflow_dispatch:
    inputs:
      mode:
        description: Verification coverage
        type: choice
        options: [full, affected]
        default: full
      request_id:
        description: Automatic release fallback correlation (leave empty for ordinary runs)
        type: string
        default: ''
permissions:
  contents: read
  actions: read
concurrency:
  group: quality-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name == 'schedule' && 'nightly' || 'change' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  select:
    name: Select affected checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      base: ${{ steps.select.outputs.base }}
      head: ${{ steps.select.outputs.head }}
      mode: ${{ steps.select.outputs.mode }}
      has_checks: ${{ steps.select.outputs.has_checks }}
      matrix: ${{ steps.select.outputs.matrix }}
      runtimes: ${{ steps.select.outputs.runtimes }}
    steps:
      - uses: actions/checkout@@@checkout@@
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@@@setup-python@@
        with:
          python-version: '@@PYTHON@@'
      - id: select
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -f .quality/vendor.json ]; then python3 .quality/vendor.py verify; fi
          python3 .quality/ci.py select
      - uses: actions/upload-artifact@@@upload-artifact@@
        if: always()
        with:
          name: quality-selection
          path: .quality-results/*.json
          include-hidden-files: true
          retention-days: 30
          if-no-files-found: error

  checks:
    name: Checks (${{ matrix.runner }})
    needs: select
    if: ${{ needs.select.outputs.has_checks == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.select.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@@@checkout@@
        with:
          ref: ${{ needs.select.outputs.head }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@@@setup-python@@
        with:
          python-version: '${{ fromJSON(needs.select.outputs.runtimes).python }}'
      - uses: actions/setup-node@@@setup-node@@
        if: ${{ fromJSON(needs.select.outputs.runtimes).node != '' }}
        with:
          node-version: '${{ fromJSON(needs.select.outputs.runtimes).node }}'
      - name: Pinned package manager
        if: ${{ fromJSON(needs.select.outputs.runtimes).pnpm != '' }}
        env:
          PNPM_VERSION: ${{ fromJSON(needs.select.outputs.runtimes).pnpm }}
        run: npm install --global "pnpm@$PNPM_VERSION" --ignore-scripts
      - uses: actions/cache@@@cache@@
        id: downloads
        if: ${{ matrix.bootstrap }}
        with:
          path: |
            .quality-cache/npm
            .quality-cache/pnpm
            .quality-cache/pip
            .quality-cache/ms-playwright
@@CACHE_PATHS@@
          key: quality-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.quality.json', '.quality/**', '**/package-lock.json', '**/pnpm-lock.yaml', '**/uv.lock', '**/requirements*.txt', '**/Cargo.lock', '**/next.config.*', '**/tsconfig.json') }}
      - name: Bootstrap disposable test environment
        if: ${{ matrix.bootstrap }}
        env:
          QUALITY_RUNNER: ${{ matrix.runner }}
        run: |
          if [ -f .quality/vendor.json ]; then python3 .quality/vendor.py verify; fi
          python3 .quality/quality.py doctor
          python3 .quality/quality.py bootstrap --runner "$QUALITY_RUNNER"
      - name: Run selected checks once
        env:
          QUALITY_BASE: ${{ needs.select.outputs.base }}
          QUALITY_HEAD: ${{ needs.select.outputs.head }}
          QUALITY_MODE: ${{ needs.select.outputs.mode }}
          QUALITY_CACHE_HIT: ${{ steps.downloads.outputs.cache-hit }}
          QUALITY_RUNNER: ${{ matrix.runner }}
        run: |
          command=run
          if [ "$QUALITY_MODE" = full ]; then command=full; fi
          python3 .quality/quality.py "$command" --base "$QUALITY_BASE" --head "$QUALITY_HEAD" --runner "$QUALITY_RUNNER" --evidence-dir .quality-checks
      - uses: actions/upload-artifact@@@upload-artifact@@
        if: always()
        with:
          name: checks-${{ matrix.runner }}
          path: |
            .quality-checks/*.json
            .quality-checks/*.log
          include-hidden-files: true
          retention-days: 30
          if-no-files-found: error
@@DIAGNOSTICS@@

  quality:
    name: Quality
    needs: [select, checks]
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@@@checkout@@
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@@@setup-python@@
        with:
          python-version: '@@PYTHON@@'
      - uses: actions/download-artifact@@@download-artifact@@
        with:
          name: quality-selection
          path: .quality-results
      - uses: actions/download-artifact@@@download-artifact@@
        if: ${{ needs.select.outputs.has_checks == 'true' }}
        with:
          pattern: checks-*
          path: .quality-results/checks
          merge-multiple: true
      - name: Reject incomplete or failed verification
        if: always()
        env:
          QUALITY_NEEDS: ${{ toJSON(needs) }}
        run: |
          mkdir -p .quality-results
          python3 -c 'import os,pathlib; pathlib.Path(".quality-results/needs.json").write_text(os.environ["QUALITY_NEEDS"])'
          python3 .quality/ci.py aggregate
      - uses: actions/upload-artifact@@@upload-artifact@@
        if: always()
        with:
          name: quality-evidence
          path: .quality-results/**/*.json
          include-hidden-files: true
          retention-days: 30
          if-no-files-found: error
'''


def render(manifest):
    result = TEMPLATE
    for name, sha in PINS.items():
        result = result.replace('@@@' + name + '@@', '@' + sha)
    minute = int(manifest.get('ci', {}).get('nightly_minute', 17))
    if not 0 <= minute <= 59:
        raise ValueError('nightly_minute must be 0..59')
    extras = manifest.get('ci', {}).get('compilation_caches', [])
    allowed = {'.next/cache', 'apps/web/.next/cache', '.turbo', 'target', 'src-tauri/target', '.mypy_cache', '.quality-cache/cargo/registry', '.quality-cache/cargo/git'}
    if not set(extras) <= allowed:
        raise ValueError('Compilation cache paths must be explicitly safe; databases and secrets are never cached')
    replacements = {'BRANCH': json.dumps(manifest.get('default_branch', 'main')),
                    'MINUTE': str(minute), 'PYTHON': manifest['runtimes']['python'],
                    'CACHE_PATHS': '\n'.join('            ' + path for path in extras)}
    for key, value in replacements.items():
        result = result.replace('@@' + key + '@@', value)
    ci = manifest.get('ci', {})
    setup = ''
    prerequisites = ''
    packages = ci.get('system_packages', [])
    if not set(packages) <= {'ripgrep', 'openssl'}:
        raise ValueError('System packages require an explicit supported prerequisite')
    if packages:
        prerequisites += "      - name: Linux test prerequisites\n        if: ${{ matrix.bootstrap && runner.os == 'Linux' }}\n        run: sudo apt-get update && sudo apt-get install --yes " + ' '.join(packages) + '\n'
    if ci.get('supabase_cli'):
        prerequisites += '''      - uses: supabase/setup-cli@46f7f98c7f948ad727d22c1e67fab04c223a0520 # v3.0.0
        if: ${{ matrix.bootstrap }}
        with:
          version: 'VERSION'
'''.replace('VERSION', ci['supabase_cli'])
    runtimes = manifest['runtimes']
    if runtimes.get('npm'):
        prerequisites += "      - run: npm install --global npm@" + runtimes['npm'] + " --ignore-scripts\n"
    if runtimes.get('uv'):
        prerequisites += "      - run: python3 -m pip install --disable-pip-version-check uv==" + runtimes['uv'] + "\n"
    if runtimes.get('rust'):
        prerequisites += "      - name: Pinned Rust toolchain\n        if: ${{ matrix.bootstrap }}\n        run: rustup toolchain install " + runtimes['rust'] + " --profile minimal --component clippy,rustfmt && rustup default " + runtimes['rust'] + "\n"
    if ci.get('browser'):
        browsers = ci['browser'] if isinstance(ci['browser'], list) else [ci['browser']]
        if not browsers or not set(browsers) <= {'chromium', 'firefox', 'webkit'}:
            raise ValueError('Unsupported browser')
        folder = ci.get('browser_directory', '.')
        if folder.startswith('/') or '..' in folder.split('/'):
            raise ValueError('Browser setup requires repository-relative directory')
        installer = ci.get('browser_installer', 'npx --no-install playwright')
        if installer not in {'npx --no-install playwright', '.venv/bin/python -m playwright'}:
            raise ValueError('Unsupported browser installer')
        setup += '''      - name: Browser runtime and Linux libraries
        if: ${{ matrix.bootstrap }}
        working-directory: FOLDER
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.quality-cache/ms-playwright
        run: INSTALLER install --with-deps BROWSER
'''.replace('FOLDER', json.dumps(folder)).replace('INSTALLER', installer).replace('BROWSER\n', ' '.join(browsers)+'\n')
    result = result.replace('      - name: Bootstrap disposable test environment\n', prerequisites + '      - name: Bootstrap disposable test environment\n')
    result = result.replace('      - name: Run selected checks once\n', setup + '      - name: Run selected checks once\n')
    diagnostics = ci.get('diagnostic_paths', [])
    permitted = {'test-results/playwright.json', 'apps/web/test-results/playwright.json', 'playwright-report', 'apps/web/playwright-report'}
    if not set(diagnostics) <= permitted:
        raise ValueError('Diagnostic artifacts require explicit safe paths')
    diagnostic_step = ''
    if diagnostics:
        diagnostic_step = '''      - uses: actions/upload-artifact@PIN
        if: always()
        with:
          name: diagnostics-${{ matrix.runner }}
          path: |
PATHS
          retention-days: 14
          if-no-files-found: ignore
'''.replace('PIN', PINS['upload-artifact']).replace('PATHS', '\n'.join('            '+p for p in diagnostics))
    if ci.get('api_image_artifact'):
        if manifest.get('release', {}).get('kind') != 'fly':
            raise ValueError('API image upload requires the declared Fly release adapter')
        diagnostic_step += '''      - name: Retain the tested API image
        uses: actions/upload-artifact@PIN
        if: ${{ success() && matrix.runner == 'ubuntu-24.04' && hashFiles('.quality-results/images/api-image.json') != '' }}
        with:
          name: quality-api-image
          path: |
            .quality-results/images/api.tar.gz
            .quality-results/images/api-image.json
          include-hidden-files: true
          retention-days: 7
          if-no-files-found: error
'''.replace('PIN', PINS['upload-artifact'])
    result = result.replace('@@DIAGNOSTICS@@', diagnostic_step)
    return result


def render_release(manifest):
    if manifest.get('release', {}).get('kind') != 'vercel':
        return None
    text = '''# Generated by .quality/workflow.py. Requires an existing reusable team deployment token.
name: Verified release
on:
  workflow_run:
    workflows: [Quality]
    types: [completed]
    branches: [BRANCH]
  workflow_dispatch:
permissions:
  contents: read
  actions: write
  deployments: write
concurrency:
  group: production-release
  cancel-in-progress: false
jobs:
  release:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == github.repository) }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@CHECKOUT
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@PYTHON_ACTION
        with:
          python-version: 'PYTHON_VERSION'
      - uses: actions/setup-node@NODE_ACTION
        with:
          node-version: 'NODE_VERSION'
PACKAGE_MANAGER
      - name: Verify pinned tooling
        run: python3 .quality/vendor.py verify
      - uses: actions/cache@CACHE
        with:
          path: |
            .quality-cache/npm
            .quality-cache/pnpm
            .quality-cache/ms-playwright
          key: release-downloads-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.quality.json', '**/package-lock.json', '**/pnpm-lock.yaml') }}
      - name: Install smoke dependencies without production credentials
        run: python3 .quality/quality.py bootstrap --runner ubuntu-24.04
BROWSER_SETUP
      - name: Verify coverage, stage production, smoke, promote and observe
        env:
          GH_TOKEN: ${{ github.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.quality-cache/ms-playwright
          QUALITY_CANDIDATE: ${{ github.event.workflow_run.head_sha || github.sha }}
        run: python3 .quality/release.py --candidate "$QUALITY_CANDIDATE"
      - uses: actions/upload-artifact@UPLOAD
        if: always()
        with:
          name: release-evidence
          path: .quality-release/*.json
          include-hidden-files: true
          retention-days: 90
          if-no-files-found: warn
'''
    replacements = {'BRANCH':json.dumps(manifest.get('default_branch','main')), 'CHECKOUT':PINS['checkout'],
                    'PYTHON_ACTION':PINS['setup-python'],'NODE_ACTION':PINS['setup-node'],
                    'PYTHON_VERSION':manifest['runtimes']['python'],'NODE_VERSION':manifest['runtimes'].get('node','22.23.1'),
                    'CACHE':PINS['cache'],'UPLOAD':PINS['upload-artifact']}
    for key,value in replacements.items():
        text=text.replace(key,value)
    pnpm=manifest['runtimes'].get('pnpm')
    manager='      - run: npm install --global pnpm@'+pnpm+' --ignore-scripts' if pnpm else ''
    if manifest['runtimes'].get('npm'):
        manager += '\n      - run: npm install --global npm@'+manifest['runtimes']['npm']+' --ignore-scripts'
    text=text.replace('PACKAGE_MANAGER',manager)
    browser=''
    if manifest.get('ci',{}).get('browser'):
        browser='''      - name: Install smoke browser
        working-directory: DIR
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.quality-cache/ms-playwright
        run: npx --no-install playwright install --with-deps chromium
'''.replace('DIR',json.dumps(manifest.get('ci',{}).get('browser_directory','.')))
    return text.replace('BROWSER_SETUP',browser)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render(json.loads(Path('.quality.json').read_text()))
    path = Path('.github/workflows/quality.yml')
    if args.check:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit('Quality workflow differs from adapter; run python3 .quality/workflow.py')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)
    release_workflow = render_release(json.loads(Path('.quality.json').read_text()))
    if release_workflow:
        release_path=Path('.github/workflows/quality-release.yml')
        if args.check:
            if not release_path.exists() or release_path.read_text()!=release_workflow:
                raise SystemExit('Release workflow differs from adapter; regenerate')
        else:
            release_path.write_text(release_workflow)
